# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
builds:
  # - binary: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}."
  - binary: "malamtime"
    id: mt-common
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/malamtime/cli/main.GitCommit={{ .Env.VERSION }}
  - binary: "malamtime"
    id: mt-mac
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/malamtime/cli/main.GitCommit={{ .Env.VERSION }}
    # hooks:
    #   post:
    #     - cmd: quill sign-and-notarize "{{ .Path }}" --dry-run={{ .IsSnapshot }} --ad-hoc={{ .IsSnapshot }} -vv
archives:
  - format: tar.gz
    id: mt-common
    builds:
      - mt-common
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
  - format: zip
    id: mac
    builds:
      - mt-mac
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: malamtime
    name: cli
  draft: false
  replace_existing_draft: false
  target_commitish: "{{ .Commit }}"
  prerelease: "false"
  mode: replace
  header: |
    ## malamtime CLI ({{ .Date }})
    Welcome to this new release!
    please download your version and put it into your $PATH
  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}!
  name_template: "v{{.Version}}"
  disable: false
  skip_upload: false
  include_meta: true
  # extra_files:
  # - glob: ./dist/cli_Darwin_*.zip
  #   - glob: ./dist/*.tar.gz
  #   - glob: ./dist/checksums.txt
notarize:
  macos:
    - enabled: '{{ isEnvSet "QUILL_SIGN_P12" }}'
      ids:
        - mt-mac
      sign:
        certificate: "{{.Env.QUILL_SIGN_P12}}"
        password: "{{.Env.QUILL_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.QUILL_NOTARY_ISSUER}}"
        key_id: "{{.Env.QUILL_NOTARY_KEY_ID}}"
        key: "{{.Env.QUILL_NOTARY_KEY}}"
        wait: true
